import { ProjectConfig, GeneratedFile, GenerationResult } from "./types";

export function generateProject(config: ProjectConfig): GenerationResult {
  const files: GeneratedFile[] = [];
  const components: string[] = [];

  // Create DevOps directory structure
  const dirs = [
    "pipelines",
    "infrastructure",
    "infrastructure/modules",
    "infrastructure/environments",
    "deployments",
    "deployments/helm",
    "deployments/kustomize",
    "monitoring",
    "monitoring/dashboards",
    "monitoring/alerts",
    "security",
    "security/policies",
    "security/compliance",
    "scripts",
    "docs",
    "tests",
  ];

  // Add pipeline-specific directories
  if (config.pipeline) {
    switch (config.pipeline) {
      case "terraform-module":
        dirs.push("terraform", "terraform/examples", "terraform/test");
        break;
      case "kubernetes-operator":
        dirs.push("operator", "operator/config", "operator/controllers");
        break;
      case "microservice":
        dirs.push("services", "gateway", "shared");
        break;
    }
  }

  // Add infrastructure-specific directories
  if (config.infra) {
    switch (config.infra) {
      case "aws-vpc-eks":
      case "azure-vnet-aks":
      case "gcp-vpc-gke":
        dirs.push("kubernetes", "kubernetes/manifests");
        break;
    }
  }

  for (const dir of dirs) {
    files.push({ path: `${config.projectName}/${dir}`, content: "", type: "directory" });
  }

  // Base files (always generated)
  files.push(...generateBaseFiles(config));
  components.push("Base");

  // Pipeline files
  files.push(...generatePipelineFiles(config));
  components.push(`Pipeline: ${config.pipeline}`);

  // CI/CD files
  if (config.ci && config.ci !== "none") {
    files.push(...generateCIFiles(config));
    components.push("CI/CD");
  }

  // Infrastructure files
  files.push(...generateInfraFiles(config));
  components.push("Infrastructure");

  // Deployment files
  files.push(...generateDeployFiles(config));
  components.push("Deployment");

  // Monitoring files
  files.push(...generateMonitoringFiles(config));
  components.push("Monitoring");

  // Security files
  files.push(...generateSecurityFiles(config));
  components.push("Security");

  const totalDirs = files.filter((f) => f.type === "directory").length;
  const totalFiles = files.filter((f) => f.type === "file").length;

  return {
    success: true,
    projectName: config.projectName,
    files,
    summary: { totalFiles, totalDirs, components },
  };
}

function getEnvList(config: ProjectConfig): string[] {
  if (config.envs === "single") return ["dev"];
  return config.envs.split(",").map((e) => e.trim());
}

function generateBaseFiles(config: ProjectConfig): GeneratedFile[] {
  const envs = getEnvList(config);
  const slug = config.projectName.toLowerCase().replace(/_/g, "-");

  return [
    {
      path: `${config.projectName}/README.md`,
      type: "file",
      content: `# ${config.projectName}

> Generated by DevOps Project Generator v1.6.0

## DevOps Stack Overview

| Component           | Selection                    |
|---------------------|------------------------------|
| Pipeline Framework  | ${config.pipeline}           |
| CI/CD Platform      | ${config.ci}                 |
| Infrastructure      | ${config.infra}              |
| Deployment Strategy | ${config.deploy}             |
| Environments        | ${envs.join(", ")}           |
| Observability       | ${config.observability}      |
| Security Framework  | ${config.security}           |

## Getting Started

\`\`\`bash
# Setup the project
make setup

# Run locally
make run

# Deploy
make deploy
\`\`\`

## Project Structure

\`\`\`
${config.projectName}/
├── app/              # Application source code
├── ci/               # CI/CD pipeline configurations
├── infra/            # Infrastructure as Code
├── deploy/           # Deployment configurations
├── k8s/              # Kubernetes manifests
├── monitoring/       # Observability configs
├── security/         # Security policies & scanning
├── scripts/          # Utility scripts
├── docs/             # Documentation
└── tests/            # Test suites
\`\`\`

## Environments

${envs.map((e) => `- **${e}**`).join("\n")}

## License

MIT
`,
    },
    {
      path: `${config.projectName}/Makefile`,
      type: "file",
      content: `# ${config.projectName} Makefile
# Generated by DevOps Project Generator

.PHONY: help setup run test deploy clean lint

help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'

setup: ## Setup the project
\t@echo "Setting up ${config.projectName}..."
\t@bash scripts/setup.sh

run: ## Run the application locally
\t@echo "Running ${config.projectName}..."
${config.deploy === "helm-charts" || config.deploy === "kustomize" ? "\t@docker-compose up --build" : "\t@echo 'Deployment strategy: " + config.deploy + "'"}

test: ## Run tests
\t@echo "Running tests..."
\t@cd tests && python -m pytest -v

deploy: ## Deploy the application
\t@echo "Deploying ${config.projectName}..."
\t@bash scripts/deploy.sh

clean: ## Clean build artifacts
\t@echo "Cleaning..."
\t@find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
\t@find . -type f -name "*.pyc" -delete 2>/dev/null || true

lint: ## Run linters
\t@echo "Linting..."
\t@flake8 app/ --max-line-length=120

${config.deploy === "helm-charts" || config.deploy === "kustomize" ? `docker-build: ## Build Docker image
\t@docker build -t ${slug}:latest -f deploy/Dockerfile .

docker-push: ## Push Docker image
\t@docker push ${slug}:latest` : ""}
`,
    },
    {
      path: `${config.projectName}/.gitignore`,
      type: "file",
      content: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
*.egg
.eggs/
venv/
.env

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Docker
.docker/

# Terraform
.terraform/
*.tfstate
*.tfstate.*
*.tfvars

# Kubernetes
*.kubeconfig

# Logs
*.log
logs/

# Coverage
htmlcov/
.coverage
`,
    },
    {
      path: `${config.projectName}/app/sample-app/main.py`,
      type: "file",
      content: `#!/usr/bin/env python3
"""
${config.projectName} - Sample Application
Generated by DevOps Project Generator
"""

import os
import logging
from http.server import HTTPServer, BaseHTTPRequestHandler

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PORT = int(os.environ.get("PORT", 8080))
ENV = os.environ.get("ENVIRONMENT", "development")


class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"status": "healthy", "service": "${config.projectName}"}')
        elif self.path == "/":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(f"${config.projectName} running in {ENV}".encode())
        else:
            self.send_response(404)
            self.end_headers()


if __name__ == "__main__":
    server = HTTPServer(("0.0.0.0", PORT), HealthHandler)
    logger.info(f"Starting ${config.projectName} on port {PORT} (env: {ENV})")
    server.serve_forever()
`,
    },
    {
      path: `${config.projectName}/app/sample-app/requirements.txt`,
      type: "file",
      content: `# ${config.projectName} dependencies
flask>=2.3.0
gunicorn>=21.2.0
requests>=2.31.0
python-dotenv>=1.0.0
`,
    },
    {
      path: `${config.projectName}/scripts/setup.sh`,
      type: "file",
      content: `#!/bin/bash
# Setup script for ${config.projectName}
# Generated by DevOps Project Generator

set -euo pipefail

echo "🚀 Setting up ${config.projectName}..."

# Create virtual environment
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo "✅ Virtual environment created"
fi

# Activate and install deps
source venv/bin/activate
pip install -r app/sample-app/requirements.txt
echo "✅ Dependencies installed"

echo "🎉 Setup complete! Run 'make run' to start."
`,
    },
    {
      path: `${config.projectName}/scripts/deploy.sh`,
      type: "file",
      content: `#!/bin/bash
# Deploy script for ${config.projectName}
# Generated by DevOps Project Generator

set -euo pipefail

ENVIRONMENT=\${1:-dev}

echo "🚀 Deploying ${config.projectName} to \${ENVIRONMENT}..."

${config.deploy === "helm-charts" ? `helm upgrade --install ${slug} ./deployments/helm --namespace=${slug}-\${ENVIRONMENT} --create-namespace
echo "✅ Helm chart deployed"` : ""}
${config.deploy === "kustomize" ? `kubectl apply -k deployments/kustomize/overlays/\${ENVIRONMENT}
echo "✅ Kustomize manifests applied"` : ""}
${config.deploy === "blue-green" ? `echo "Executing blue-green deployment..."
kubectl apply -f deployments/blue-green.yaml
echo "✅ Blue-green deployment initiated"` : ""}
${config.deploy === "canary" ? `echo "Executing canary deployment..."
kubectl apply -f deployments/canary.yaml
echo "✅ Canary deployment initiated"` : ""}

echo "🎉 Deployment to \${ENVIRONMENT} complete!"
`,
    },
  ];
}

function generateCIFiles(config: ProjectConfig): GeneratedFile[] {
  const slug = config.projectName.toLowerCase().replace(/_/g, "-");
  const files: GeneratedFile[] = [];

  if (config.ci === "github-actions") {
    files.push({
      path: `${config.projectName}/ci/github-actions.yml`,
      type: "file",
      content: `# GitHub Actions CI/CD Pipeline
# Generated by DevOps Project Generator

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  APP_NAME: ${slug}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/sample-app/requirements.txt
      - name: Run tests
        run: python -m pytest tests/ -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Lint
        run: |
          pip install flake8
          flake8 app/ --max-line-length=120
${config.deploy === "helm-charts" || config.deploy === "kustomize" || config.deploy === "blue-green" || config.deploy === "canary" ? `
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${slug}:\${{ github.sha }} .
      - name: Push Docker image
        run: |
          echo "\${{ secrets.DOCKER_PASSWORD }}" | docker login -u "\${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${slug}:\${{ github.sha }}` : ""}
`,
    });
  }

  if (config.ci === "gitlab-ci") {
    files.push({
      path: `${config.projectName}/ci/.gitlab-ci.yml`,
      type: "file",
      content: `# GitLab CI/CD Pipeline
# Generated by DevOps Project Generator

stages:
  - test
  - lint
  - build
  - deploy

variables:
  APP_NAME: ${slug}
  PIP_CACHE_DIR: "\$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r app/sample-app/requirements.txt
    - python -m pytest tests/ -v

lint:
  stage: lint
  image: python:3.11-slim
  script:
    - pip install flake8
    - flake8 app/ --max-line-length=120
${config.deploy === "helm-charts" || config.deploy === "kustomize" || config.deploy === "blue-green" || config.deploy === "canary" ? `
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ${slug}:\$CI_COMMIT_SHA .
    - docker push ${slug}:\$CI_COMMIT_SHA
  only:
    - main` : ""}
`,
    });
  }

  if (config.ci === "jenkins") {
    files.push({
      path: `${config.projectName}/ci/Jenkinsfile`,
      type: "file",
      content: `// Jenkins Pipeline
// Generated by DevOps Project Generator

pipeline {
    agent any

    environment {
        APP_NAME = '${slug}'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r app/sample-app/requirements.txt
                    python -m pytest tests/ -v
                '''
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    . venv/bin/activate
                    pip install flake8
                    flake8 app/ --max-line-length=120
                '''
            }
        }
${config.deploy === "helm-charts" || config.deploy === "kustomize" || config.deploy === "blue-green" || config.deploy === "canary" ? `
        stage('Build') {
            when { branch 'main' }
            steps {
                sh "docker build -t ${slug}:\${BUILD_NUMBER} ."
            }
        }

        stage('Push') {
            when { branch 'main' }
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "echo \$PASS | docker login -u \$USER --password-stdin"
                    sh "docker push ${slug}:\${BUILD_NUMBER}"
                }
            }
        }` : ""}
    }

    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
`,
    });
  }

  return files;
}

function generateDeployFiles(config: ProjectConfig): GeneratedFile[] {
  const slug = config.projectName.toLowerCase().replace(/_/g, "-");
  const files: GeneratedFile[] = [];

  if (config.deploy === "helm-charts" || config.deploy === "kustomize") {
    files.push(
      {
        path: `${config.projectName}/deploy/Dockerfile`,
        type: "file",
        content: `# Dockerfile for ${config.projectName}
# Generated by DevOps Project Generator

FROM python:3.11-slim AS base

WORKDIR /app

# Install dependencies
COPY app/sample-app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY app/sample-app/ .

# Create non-root user
RUN useradd --create-home appuser
USER appuser

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')" || exit 1

CMD ["python", "main.py"]
`,
      },
      {
        path: `${config.projectName}/deploy/docker-compose.yml`,
        type: "file",
        content: `# Docker Compose for ${config.projectName}
# Generated by DevOps Project Generator

version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=\${ENVIRONMENT:-dev}
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
`,
      }
    );
  }

  if (config.deploy === "kustomize") {
    files.push(
      {
        path: `${config.projectName}/k8s/base/deployment.yml`,
        type: "file",
        content: `# Kubernetes Deployment
# Generated by DevOps Project Generator

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${slug}
  labels:
    app: ${slug}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${slug}
  template:
    metadata:
      labels:
        app: ${slug}
    spec:
      containers:
        - name: ${slug}
          image: ${slug}:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
`,
      },
      {
        path: `${config.projectName}/k8s/base/service.yml`,
        type: "file",
        content: `# Kubernetes Service
# Generated by DevOps Project Generator

apiVersion: v1
kind: Service
metadata:
  name: ${slug}
  labels:
    app: ${slug}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ${slug}
`,
      },
      {
        path: `${config.projectName}/k8s/base/namespace.yml`,
        type: "file",
        content: `# Kubernetes Namespace
# Generated by DevOps Project Generator

apiVersion: v1
kind: Namespace
metadata:
  name: ${slug}
  labels:
    project: ${slug}
`,
      }
    );
  }

  if (config.deploy === "rolling") {
    files.push({
      path: `${config.projectName}/deploy/vm-setup.sh`,
      type: "file",
      content: `#!/bin/bash
# VM Deployment Setup for ${config.projectName}
# Generated by DevOps Project Generator

set -euo pipefail

echo "Setting up ${config.projectName} on VM..."

# Install Python
sudo apt-get update
sudo apt-get install -y python3 python3-pip python3-venv

# Create app directory
sudo mkdir -p /opt/${slug}
sudo chown \$USER:\$USER /opt/${slug}

# Setup app
cd /opt/${slug}
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

# Create systemd service
sudo cat > /etc/systemd/system/${slug}.service << EOF
[Unit]
Description=${config.projectName} Service
After=network.target

[Service]
Type=simple
User=\$USER
WorkingDirectory=/opt/${slug}
ExecStart=/opt/${slug}/venv/bin/python main.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable ${slug}
sudo systemctl start ${slug}

echo "VM setup complete!"
`,
    });
  }

  return files;
}

function generateMonitoringFiles(config: ProjectConfig): GeneratedFile[] {
  const slug = config.projectName.toLowerCase().replace(/_/g, "-");
  const files: GeneratedFile[] = [];

  // Basic security (always)
  files.push({
    path: `${config.projectName}/security/policies/security-policy.md`,
    type: "file",
    content: `# Security Policy - ${config.projectName}

## Reporting Vulnerabilities

Please report security vulnerabilities to security@example.com.

## Security Level: ${config.security}

### Implemented Controls

${config.security === "nist-csf" ? `- Basic input validation
- HTTPS enforcement
- Dependency scanning` : ""}
${config.security === "cis-benchmarks" ? `- Input validation and sanitization
- HTTPS enforcement
- Dependency scanning
- Container image scanning
- Secret management
- RBAC policies` : ""}
${config.security === "zero-trust" ? `- Comprehensive input validation
- HTTPS enforcement with HSTS
- Dependency scanning (automated)
- Container image scanning
- Secret management (Vault)
- RBAC with least privilege
- Network policies
- Pod security standards
- Audit logging
- Compliance checks` : ""}
`,
  });

  if (config.observability === "prometheus-grafana" || config.observability === "elk-stack") {
    files.push({
      path: `${config.projectName}/monitoring/metrics/prometheus.yml`,
      type: "file",
      content: `# Prometheus Configuration for ${config.projectName}
# Generated by DevOps Project Generator

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: '${slug}'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
`,
    });
  }

  if (config.observability === "elk-stack") {
    files.push({
      path: `${config.projectName}/monitoring/alerts/alerts.yml`,
      type: "file",
      content: `# Alert Rules for ${config.projectName}
# Generated by DevOps Project Generator

groups:
  - name: ${slug}-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Error rate is {{ $value }}%"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High latency on {{ $labels.instance }}"

      - alert: ServiceDown
        expr: up{job="${slug}"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "${config.projectName} is down"
`,
    });
  }

  return files;
}

function generateSecurityFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Basic security (always)
  files.push({
    path: `${config.projectName}/security/policies/security-policy.md`,
    type: "file",
    content: `# Security Policy - ${config.projectName}

## Reporting Vulnerabilities

Please report security vulnerabilities to security@example.com.

## Security Level: ${config.security}

### Implemented Controls

${config.security === "nist-csf" ? `- Basic input validation
- HTTPS enforcement
- Dependency scanning` : ""}
${config.security === "cis-benchmarks" ? `- Input validation and sanitization
- HTTPS enforcement
- Dependency scanning
- Container image scanning
- Secret management
- RBAC policies` : ""}
${config.security === "zero-trust" ? `- Comprehensive input validation
- HTTPS enforcement with HSTS
- Dependency scanning (automated)
- Container image scanning
- Secret management (Vault)
- RBAC with least privilege
- Network policies
- Pod security standards
- Audit logging
- Compliance checks` : ""}
`,
  });

  if (config.security === "cis-benchmarks" || config.security === "zero-trust") {
    files.push({
      path: `${config.projectName}/security/scanning/trivy.yml`,
      type: "file",
      content: `# Trivy Security Scanner Configuration
# Generated by DevOps Project Generator

scan:
  severity: [CRITICAL, HIGH${config.security === "zero-trust" ? ", MEDIUM" : ""}]
  vuln-type: [os, library]
  ignore-unfixed: false
  exit-code: 1

image:
  scan:
    enabled: true
    fail-on: CRITICAL

filesystem:
  scan:
    enabled: true
    skip-dirs: [node_modules, .git, venv]
`,
    });
  }

  if (config.security === "zero-trust") {
    files.push({
      path: `${config.projectName}/security/policies/network-policy.yml`,
      type: "file",
      content: `# Kubernetes Network Policy
# Generated by DevOps Project Generator

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${config.projectName}-network-policy
spec:
  podSelector:
    matchLabels:
      app: ${config.projectName}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              role: database
      ports:
        - protocol: TCP
          port: 5432
`,
    });
  }

  return files;
}

function generatePipelineFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  
  switch (config.pipeline) {
    case "nodejs-typescript":
      files.push(
        {
          path: `${config.projectName}/pipelines/ci-nodejs.yml`,
          type: "file",
          content: `# Node.js TypeScript CI/CD Pipeline
# Generated by DevOps Project Generator

name: Node.js CI/CD
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: \${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Security audit
      run: npm audit --audit-level moderate
    
    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: \${{ secrets.SNYK_TOKEN }}`,
        }
      );
      break;
      
    case "terraform-module":
      files.push(
        {
          path: `${config.projectName}/terraform/main.tf`,
          type: "file",
          content: `# Terraform Module
# Generated by DevOps Project Generator

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  
  backend "s3" {
    bucket = "terraform-state-\${var.project_name}"
    key    = "terraform.tfstate"
    region = var.aws_region
  }
}

provider "aws" {
  region = var.aws_region
}

# Module example
module "vpc" {
  source = "./modules/vpc"
  
  project_name = var.project_name
  environment  = var.environment
  
  tags = local.tags
}`,
        },
        {
          path: `${config.projectName}/terraform/variables.tf`,
          type: "file",
          content: `variable "project_name" {
  description = "Name of the project"
  type        = string
}

variable "environment" {
  description = "Environment (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}`,
        }
      );
      break;
      
    case "kubernetes-operator":
      files.push(
        {
          path: `${config.projectName}/operator/config/crd/bases/example.com_customresources.yaml`,
          type: "file",
          content: `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customresources.example.com
spec:
  group: example.com
  names:
    kind: CustomResource
    listKind: CustomResourceList
    plural: customresources
    singular: customresource
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                default: 1`,
        }
      );
      break;
  }
  
  return files;
}

function generateInfraFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  
  switch (config.infra) {
    case "aws-vpc-eks":
      files.push(
        {
          path: `${config.projectName}/infrastructure/vpc.tf`,
          type: "file",
          content: `# AWS VPC Configuration
# Generated by DevOps Project Generator

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  
  tags = {
    Name        = "${config.projectName}-vpc"
    Environment = var.environment
    Project     = var.project_name
  }
}

resource "aws_subnet" "private" {
  count = 3
  
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.\${count.index + 1}.0/24"
  availability_zone = data.aws_availability_zones.available.names[count.index]
  
  tags = {
    Name                                              = "${config.projectName}-private-\${count.index + 1}"
    "kubernetes.io/cluster/${config.projectName}-eks" = "shared"
    Environment                                       = var.environment
  }
}

resource "aws_eks_cluster" "main" {
  name     = "${config.projectName}-eks"
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.28"
  
  vpc_config {
    subnet_ids = aws_subnet.private[*].id
  }
  
  depends_on = [
    aws_iam_role_policy_attachment.eks_cluster_policy,
  ]
}`,
        }
      );
      break;
      
    case "terraform-multi-cloud":
      files.push(
        {
          path: `${config.projectName}/infrastructure/main.tf`,
          type: "file",
          content: `# Multi-Cloud Infrastructure
# Generated by DevOps Project Generator

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
  }
}

# AWS Provider
provider "aws" {
  alias  = "aws"
  region = var.aws_region
}

# Azure Provider
provider "azurerm" {
  alias  = "azure"
  features {}
}

# GCP Provider
provider "google" {
  alias  = "gcp"
  project = var.gcp_project
  region  = var.gcp_region
}

# Multi-cloud networking example
module "aws_network" {
  source   = "./modules/aws-network"
  providers = {
    aws = aws.aws
  }
  
  project_name = var.project_name
  environment  = var.environment
}

module "azure_network" {
  source     = "./modules/azure-network"
  providers  = {
    azurerm = azurerm.azure
  }
  
  project_name = var.project_name
  environment  = var.environment
}`,
        }
      );
      break;
  }
  
  return files;
}
